### ISSUE TITLE
quserinterface needs copyright update

### ISSUE THREAD

**Issue by chris-hld** [SoundScapeRenderer/ssr#137]
https://github.com/SoundScapeRenderer/ssr/blob/6a67d658fc79f85e9171a868aea6765bf6b13b74/src/gui/quserinterface.cpp#L1241

**Comment by mgeier** [comment]
The mentioned institution hasn't made any substantial contributions after 2014, that's why I didn't bother to update the year.

I'm not a fan of those institutional copyright notices, that's why I've snuck in a different copyright notice recently:

https://github.com/SoundScapeRenderer/ssr/blob/6a67d658fc79f85e9171a868aea6765bf6b13b74/src/api.h#L2

**Comment by chris-hld** [comment]
Fair enough. It just caught my attention while porting stuff. Doesn't need any fixing.
