### ISSUE TITLE
--fudi-server is not recognized by ssr

### ISSUE THREAD

**Issue by brandflake11** [SoundScapeRenderer/ssr#241]
Hello ssr team,
I am trying to control ssr with ssrclient.pd. However, --fudi-server doesn't seem to be a recognized option anymore. How do I control ssr with fudi?
Here is the command I tried to do:

`ssr-binaural  ~/Downloads/live_input.asd --fudi-server`
And its output:
`ssr-binaural: unrecognized option '--fudi-server'`

Has --fudi-server been replaced with something else? The manual from January 13, 2021 still references it on page 48.

**Comment by mgeier** [comment]
Which version of the SSR are you using?

FUDI support has been added "fairly recently" (#190) and there hasn't been a new SSR release since.

So for now, you'll have to compile the `master` branch from Git yourself (see https://ssr.readthedocs.io/en/latest/building-from-source.html#git-repository).

BTW, the manual for the latest release is there: https://ssr.readthedocs.io/en/0.5.0/

And the manual for the `master` branch is there: https://ssr.readthedocs.io/en/latest/

**Comment by brandflake11** [comment]
Okay, I'll compile from the master branch and experiment then. Sorry about this confusion!
