### ISSUE TITLE
Problems on 0.5.0

### ISSUE THREAD

**Issue by differencetones** [SoundScapeRenderer/ssr#247]
Hello. As I'm starting up the latest version (0.5.0) on OSX 10.14.6 and the terminal throws back this error:

`En-Satans-Mac:~ Satan$ export ECASOUND="/Applications/SoundScapeRenderer-0.5.0/SoundScapeRenderer.app/Contents/MacOS/ecasound" ; cd "/Applications/SoundScapeRenderer-0.5.0/SoundScapeRenderer.app/Contents/MacOS/../../.." ; "/Applications/SoundScapeRenderer-0.5.0/SoundScapeRenderer.app/Contents/MacOS/ssr" --wfs && (echo SSR quit normally with exit code $?) || (echo SSR encountered an error and had to quit. See above.  Exit code: $?)
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: Error loading WFS pre-equalization filter file: apf::load_sndfile(): "SoundScapeRenderer.app/Contents/Resources/default_wfs_prefilter.wav" has sample rate 44100 instead of 48000!
/Applications/SoundScapeRenderer-0.5.0/SoundScapeRenderer.app/Contents/MacOS/ssr: line 48: 19188 Abort trap: 6           $SSR_EXECUTABLE "${OPTIONS[@]}"
SSR encountered an error and had to quit. See above. Exit code: 134`

How can you change which filter is loaded at startup? Thanks.

**Comment by JensAhrens** [comment]
The crucial part of the error message seems to be  `"default_wfs_prefilter.wav" has sample rate 44100 instead of 48000!`. So it seems that you're running JACK at 48 kHz. There are 2 options:

1. Re-start JACK with 44.1 kHz
2. Load a wfs_prefilter that is designed for 48 kHz (start SSR with the command line option `--prefilter=data/impulse_responses/wfs_prefilter_100_1300_48000.wav` or something in that spirit. I can't test right now.)

**Comment by differencetones** [comment]
Yes, perfect! Thanks!
