### ISSUE TITLE
GUI controls for multiple SSR instances

### ISSUE THREAD

**Issue by hagenw** [SoundScapeRenderer/ssr#36]
I don't know if the following is a bug or a feature, but I would prefer a different behavior.
Try the following:

``` bash
ssr-binaural -I -n SSR1 one_channel.wav & # start first SSR
ssr-binaural -I -n SSR2 one_channel.wav & # start second SSR
```

If you now press the play button on one of the SSR controls both SSRs will start the playback. I would prefer that only the one for which the play button was pressed starts with playback. This would give us the possibility to switch between different SSR instances for playback of different complex scenes consisting of several wav files (as the loading of a new complex scene could take a while).

**Comment by mgeier** [comment]
This is expected behavior.

The SSR uses the library [ecasound](http://nosignal.fi/ecasound/) for the playback of source signals.
The control of play/pause/rewind/... works via [JACK transport](http://jackaudio.org/files/docs/html/transport-design.html), i.e. the SSR doesn't directly send commands to its corresponding ecasound process(es), but just issues JACK transport commands which the ecasound process(es) listen(s) to.

Since there is only one transport per JACK daemon, all playback is synchronized, regardless how many instances of the SSR and ecasound are running at the same time.

This has the advantage that other playback applications which support the JACK transport (e.g. Ardour) can be used at the same time as the SSR (and its ecasound playback processes).

Of course it has the disadvantage that @hagenw mentioned.

Possible long term solutions:

* replace ecasound by something else

* don't use the JACK transport but send commands directly to ecasound (this might or might not work)

This is unlikely to be done soon, unless somebody volunteers ...

Possible short term solution:

* don't use the SSR's playback feature but instead use a different program (e.g. Puredata) for playback and route the audio channels via JACK to the SSR

**Comment by mgeier** [comment]
BTW, this doesn't really have anything to do with the GUI.
