### ISSUE TITLE
Code repository on bitbucket?

### ISSUE THREAD

**Issue by dennisguse** [SoundScapeRenderer/ssr#62]
I just discovered that there is an old code repository on bitbucket: https://bitbucket.org/spatialaudio/ssr

Is this still in use for something else than downloading release versions?
If not it would be great to remove it and change the links on http://spatialaudio.net/ssr/download/ to Github releases, or?

**Comment by mgeier** [comment]
Why would that be so great?

And why do you think it is old?
It is missing just a single commit, because @JensAhrens didn't push to it last time, not a big deal.

It's just a mirror, in case Github is attacked and swallowed by a giant molluscophaguous sea monster.
Mirrors are good, aren't they?

Our usage of the download section comes from an ancient time when Github decided out of the blue to disable their download section. Bitbucket didn't, which I'm grateful for.
Also, the download page has a nice download counter.

I really don't see any disadvantages here.

**Comment by dennisguse** [comment]
Well - it is not documented, which the active repository is, e.g., report bugs on github or rather on bitbucket.

I also like mirrors :)

**Comment by mgeier** [comment]
> it is not documented

Well, the Github repo is mentioned on these pages (which are the main pages everybody who wants to know about the SSR should look at):

* http://spatialaudio.net/ssr/
* http://spatialaudio.net/ssr/download/

You are right that it isn't mentioned here, where it also should be mentioned:

http://ssr.readthedocs.io/en/latest/general.html#bug-reports-feature-requests-and-comments

Can you please make a PR fixing this?
Several parts of the manual are somewhat outdated, PRs are welcome!

The Bitbucket URL is mentioned nowhere, but it doesn't mean that it's necessarily "inactive".
Anyone can make a pull request on Bitbucket if they prefer it over Github.
