### ISSUE TITLE
Build of ip-interface fails with gcc > 7

### ISSUE THREAD

**Issue by dvzrv** [SoundScapeRenderer/ssr#80]
Arch Linux recently switched to gcc > 7.
The ip-interface is not able to build with it anymore, as shown in the attached [make.txt](https://github.com/SoundScapeRenderer/ssr/files/1055148/make.txt).

Issuing a prior `./configure --disable-ip-interface` builds fine (apart from the deprecation warnings in other parts of the code base).

**Comment by mgeier** [comment]
Thanks for the report!

The `std::bind` and `std::placeholders` errors should be fixed by

    #include <functional>

The rest are warnings, right?
I think we've never really consequently used `throw` specifications for functions. I guess we should replace them with the appropriate `noexcept`. Or should we completely get rid of them?

**Comment by dvzrv** [comment]
@mgeier I can confirm, that this fixes it. #81 takes care of it.
The rest are only deprecation warnings.
