### ISSUE TITLE
Unable to run SSR with rendering algorithms

### ISSUE THREAD

**Issue by tonetechnician** [SoundScapeRenderer/ssr#83]
Hello! 

I was hoping someone could help me, I'm having trouble starting up the application in MacOSx Sierra 10.12.4. I have used the bundled version of SSR and have not yet tried to compile from source. 

I haven't been able open the application in any of the modes except BRIR mode. 

It seems as if it not able to load the default configs.

in particular I get 

    Error loading WFS pre-equalization filter file: apf::load_sndfile()

here is my console output.

```
dhcp-bfca:~ ****$ export ECASOUND="/private/var/folders/_t/67rf88lx507btn91x6g_vfk40000gp/T/AppTranslocation/42F7F94E-AED9-4F39-8647-41D898CCE032/d/SoundScapeRenderer.app/Contents/MacOS/ecasound" ; cd "/private/var/folders/_t/67rf88lx507btn91x6g_vfk40000gp/T/AppTranslocation/42F7F94E-AED9-4F39-8647-41D898CCE032/d/SoundScapeRenderer.app/Contents/MacOS/../../.." ; "/private/var/folders/_t/67rf88lx507btn91x6g_vfk40000gp/T/AppTranslocation/42F7F94E-AED9-4F39-8647-41D898CCE032/d/SoundScapeRenderer.app/Contents/MacOS/ssr" --wfs && (echo SSR quit normally with exit code $?) || (echo SSR encountered an error and had to quit. See above.  Exit code: $?)
terminate called after throwing an instance of 'std::logic_error'
  what():  Error loading WFS pre-equalization filter file: apf::load_sndfile(): "SoundScapeRenderer.app/Contents/Resources/default_wfs_prefilter.wav" couldn't be loaded!
/private/var/folders/_t/67rf88lx507btn91x6g_vfk40000gp/T/AppTranslocation/42F7F94E-AED9-4F39-8647-41D898CCE032/d/SoundScapeRenderer.app/Contents/MacOS/ssr: line 48: 36804 Abort trap: 6           $SSR_EXECUTABLE "${OPTIONS[@]}"
SSR encountered an error and had to quit. See above. Exit code: 134
```

I have installed all the dependencies using homebrew in the hopes that it would help solve the issue.

    brew update && brew upgrade && brew install autoconf fftw libsndfile jack ecasound qt asio --c++11

but still to no avail.

I would greatly appreciate it if anyone could shed some light on the issue.

Thank you!

**Comment by DastardlyMut** [comment]
Ok, so I have solved this particular problem thanks to this issue that was posted --> https://github.com/SoundScapeRenderer/ssr/issues/16

I must say that I agree with umlaeute that there should be a more descriptive explanation about the sample rate requirement for the default filters. In my particular case, I'm unable to switch to 44,1khz because my DACs are hardcoded at 48khz and up. 

My solution was to take the same default_wfs_prefilter.wav, put it into Reaper DAW and rerender with a sample rate of 48khz, however this has brought about some unwanted aliasing on the filter

![screen shot 2017-07-23 at 1 04 50 pm](https://user-images.githubusercontent.com/13471797/28498834-8eb61460-6fa7-11e7-98e5-90284fcd4edc.png)

Alright, so that sorted out that problem, but now I've run into another issue where I'm unable to load the default_setup.asd file, here is my console output.

> 'I/O warning : failed to load external entity "SoundScapeRenderer.app/Contents/Resources/default_setup.asd"
Error in xmlParseFile (SoundScapeRenderer.app/Contents/Resources/default_setup.asd)!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to load reproduction setup file "SoundScapeRenderer.app/Contents/Resources/default_setup.asd"!
/private/var/folders/_t/67rf88lx507btn91x6g_vfk40000gp/T/AppTranslocation/42F7F94E-AED9-4F39-8647-41D898CCE032/d/SoundScapeRenderer.app/Contents/MacOS/ssr: line 48: 37343 Abort trap: 6           $SSR_EXECUTABLE "${OPTIONS[@]}"
SSR encountered an error and had to quit. See above. Exit code: 134'

I'm unsure as to why this might be happening, any help would be appreciated!

Thanks!

**Comment by mgeier** [comment]
Are you able to find the file `SoundScapeRenderer.app/Contents/Resources/default_setup.asd` in the Finder?

How did you install the SSR?

The path looks very suspicious:

    /private/var/folders/_t/67rf88lx507btn91x6g_vfk40000gp/T/AppTranslocation/42F7F94E-AED9-4F39-8647-41D898CCE032/d/

**Comment by mgeier** [comment]
> [...] put it into Reaper DAW and rerender with a sample rate of 48khz, however this has brought about some unwanted aliasing on the filter

There is no aliasing when upsampling, probably Reaper just messed it up. It's probably not the best tool for that.

I recommend using SoX for sample rate conversion: http://sox.sourceforge.net/

They have a macOS installer and it is also available for Homebrew.

**Comment by DastardlyMut** [comment]
Hey! Thank you so much for the reply. 

> I recommend using SoX for sample rate conversion: http://sox.sourceforge.net/

I will give it a try with SoX, thank you for the suggestion! 

I installed it using the application bundle (.dmg file). I dragged the whole SoundScapeRenderer-0.4.2 directory into my applications folder and have been trying to run it from there.

> Are you able to find the file SoundScapeRenderer.app/Contents/Resources/default_setup.asd in the Finder?

Yes, I am able to find it exactly where you have specified.

Should I try compile from source?

Many thanks!

**Comment by mgeier** [comment]
A quick web search for "private var folders AppTranslocation" suggests that this is caused by a new security feature in Sierra:

Some random links:
https://stackoverflow.com/questions/40251201/upgrading-intellij-idea-after-sierra-upgrade-does-not-have-write-access-to-pri
https://lapcatsoftware.com/articles/app-translocation.html
https://eclecticlight.co/2016/06/16/macos-sierra-will-break-many-installers-and-updaters/
http://krypted.com/mac-security/app-translocation-services-os-x-10-12/

I don't understand any of this and I don't know if we can do anything to fix it from the SSR side.
Any suggestions anyone?

@DastardlyMut If you are willing to compile from source and you don't use the App Bundle, I guess it should work fine. But I don't know ...

**Comment by chohner** [comment]
I got it to run on macOS Sierra:

```
xattr -d com.apple.quarantine SoundScapeRenderer.app
```

**Comment by DastardlyMut** [comment]
Thanks so much for the help Matthias and Chohner. 

I can confirm that this solved my issue

`xattr -d com.apple.quarantine SoundScapeRenderer.app`

Now to get Jack working within the AVB context.

Thanks again!
